apiVersion: v1
kind: Service
metadata:
  name: sre-playground
  namespace: sre-playground
  labels:
    app: sre-playground
spec:
  type: ClusterIP
  selector:
    app: sre-playground
  ports:
    - name: http
      port: 80
      targetPort: 8080
